version: '3'
services:
  api-gateway:
    build: './api-gateway'
    depends_on:
      - school-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  school-service:
    build: './school-service'
    depends_on:
      - school-service-db
    environment:
      - DB_URI=mysql://root:password@school-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./school-service:/opt/app

  school-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: './users-service'
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
